[GLOBAL]
pants_version = "2.29.1"

backend_packages = [
  "pants.backend.python",
  "pants.backend.experimental.python",
]

[python]
interpreter_constraints = ["~=3.11.0"]
enable_resolves = true

[python.resolves]
single = "single_resolve/lockfile"
